#!/bin/sh

# TODO: list and select from tags first (or else results are overwhelmed by watch-later)
#				or maybe exclude watch-later and things like it, by default

tag="$1"

buku_flag="-p"
if [ "$tag" != "" ]; then
	buku_flag="--stag $tag"
fi

buku --nostdin $buku_flag -f 4 \
	| sed 's/\t/ /g' \
	| dmenu -b -i -l 10 \
	| cut -d ' ' -f 2
