#!/bin/sh

SCRIPT_DIR="$HOME/.local/share/qutebrowser/userscripts/"

mkdir -p $SCRIPT_DIR
cp qute-buku $SCRIPT_DIR

# NOTE: Setting the keybinding is handled in qutebrowser config.
#				Should this be part of install?
