#!/bin/sh

# TODO: Should probably check if qutebrowser is actually installed
SCRIPT_DIR="$HOME/.local/share/qutebrowser/userscripts/"
mkdir -p $SCRIPT_DIR
cp qute-buku qute-bukuopen $SCRIPT_DIR

BIN_DIR="$HOME/bin/"
mkdir -p $BIN_DIR
cp bukumenu bukuopen $BIN_DIR

# NOTE: Setting the keybinding is handled in qutebrowser config.
#				Should this be part of install?

# Config pieces that go with this:
# - browser bindings
# - os-level bindings
# ...
