#!/bin/sh

# TODO: Rename to 'qute-bukuadd'
# TODO: Have the ability to choose the tag (eg to select watch-later with a different bind)

buku --debug --add "$QUTE_URL" web --title "$QUTE_TITLE" >> /dev/null 2>&1
echo "message-info 'Bookmark added to Buku!'" >> "$QUTE_FIFO"
